# Generated by Django 2.0.2 on 2018-02-09 10:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

from ..sql.sqldataloaders import public_holiday_data


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicHolidayCalendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created')),
                ('updated', models.DateTimeField(blank=True, null=True, verbose_name='Updated')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.Community')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.Country')),
                ('locality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.Locality')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.Province')),
            ],
            options={
                'verbose_name_plural': 'Public Holiday Calendars',
                'ordering': ['date'],
                'verbose_name': 'Public Holiday Calendar',
            },
        ),
        migrations.RunPython(public_holiday_data),
    ]
