# Generated by Django 2.0.2 on 2018-02-06 18:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutonomousCommunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Autonomous Community')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created')),
                ('updated', models.DateTimeField(blank=True, null=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'Autonomous Community',
                'verbose_name_plural': 'Autonomous Communities',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Country')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created')),
                ('updated', models.DateTimeField(blank=True, null=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Locality')),
                ('is_apeteat', models.BooleanField(default=False, verbose_name='Is ApetEat service')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created')),
                ('updated', models.DateTimeField(blank=True, null=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'Locality',
                'verbose_name_plural': 'Localities',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Province')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created')),
                ('updated', models.DateTimeField(blank=True, null=True, verbose_name='Updated')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publicholidays.AutonomousCommunity')),
            ],
        ),
        migrations.CreateModel(
            name='PublicHolidaysCalendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Date')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created')),
                ('updated', models.DateTimeField(blank=True, null=True, verbose_name='Updated')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publicholidays.AutonomousCommunity')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publicholidays.Country')),
                ('localities', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publicholidays.Locality')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publicholidays.Province')),
            ],
        ),
        migrations.AddField(
            model_name='locality',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publicholidays.Province'),
        ),
        migrations.AddField(
            model_name='autonomouscommunity',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publicholidays.Country'),
        ),
    ]
